version: "3.9"

services:
  gmaps-scraper:
    image: gosom/google-maps-scraper:latest
    container_name: gmaps-scraper
    expose:
      - "8080"
    networks:
      - web
    volumes:
      - ./gmapsdata:/gmapsdata
    command: ["-addr", ":8080", "-data-folder", "/gmapsdata", "-email"]
    restart: unless-stopped

  frontend:
    image: nginx:stable-alpine
    container_name: gmaps-frontend
    expose:
      - "80"
    networks:
      - web
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./gmapsdata:/usr/share/nginx/html/gmapsdata:ro
      - /opt/ssl/saikanov:/etc/nginx/ssl:ro # ssl certificates
    depends_on:
      - gmaps-scraper
    restart: unless-stopped
